/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#e0bec4",
        primary: "#7f5047",
        "inverse-on-surface": "#f3f0ef",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#33110b",
        "inverse-surface": "#313030",
        "on-primary-container": "#fffbff",
        "on-error": "#ffffff",
        "on-surface": "#1c1b1b",
        "on-secondary-fixed-variant": "#594045",
        tertiary: "#7b5149",
        "primary-fixed": "#ffdad4",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1b1b",
        "primary-container": "#9b685e",
        outline: "#847371",
        "surface-container-lowest": "#ffffff",
        secondary: "#72575d",
        "surface-container-high": "#ebe7e7",
        "tertiary-fixed": "#ffdad3",
        error: "#ba1a1a",
        "primary-fixed-dim": "#f6b8ad",
        "secondary-container": "#fad7dd",
        "on-tertiary-fixed": "#30130d",
        "on-secondary-container": "#765c61",
        "surface-variant": "#e5e2e1",
        "surface-tint": "#825249",
        surface: "#fcf9f8",
        "on-surface-variant": "#514441",
        "secondary-fixed": "#fddae0",
        "surface-container": "#f0edec",
        "surface-container-low": "#f6f3f2",
        "outline-variant": "#d6c2bf",
        "on-secondary-fixed": "#29161b",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#633d35",
        "surface-container-highest": "#e5e2e1",
        "inverse-primary": "#f6b8ad",
        "on-primary-fixed-variant": "#673b33",
        "on-tertiary-container": "#fffbff",
        "surface-dim": "#dcd9d9",
        "tertiary-container": "#966961",
        "tertiary-fixed-dim": "#f0baaf",
        background: "#fcf9f8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-2xl": "4rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        margin: "3.5rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "headline-xl-mobile": ["Bodoni Moda"],
        "headline-lg": ["Bodoni Moda"],
        "headline-sm": ["Bodoni Moda"],
        "headline-md": ["Bodoni Moda"],
        "headline-xl": ["Bodoni Moda"],
        "body-lg": ["Montserrat"],
        "body-md": ["Montserrat"],
        "label-sm": ["Montserrat"],
        "label-lg": ["Montserrat"],
        "body-sm": ["Montserrat"],
        "label-md": ["Montserrat"],
        "headline-lg-mobile": ["Bodoni Moda"],
      },
      fontSize: {
        "headline-xl-mobile": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "headline-lg": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "headline-sm": [
          "22px",
          {
            lineHeight: "28px",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
        "headline-md": [
          "28px",
          { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" },
        ],
        "headline-xl": [
          "56px",
          {
            lineHeight: "64px",
            letterSpacing: "-0.02em",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "16px",
          {
            lineHeight: "26px",
            letterSpacing: "0.01em",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "14px",
          {
            lineHeight: "22px",
            letterSpacing: "0.02em",
            fontWeight: "400",
          },
        ],
        "label-sm": [
          "9px",
          {
            lineHeight: "12px",
            letterSpacing: "0.2em",
            fontWeight: "600",
          },
        ],
        "label-lg": [
          "13px",
          {
            lineHeight: "16px",
            letterSpacing: "0.12em",
            fontWeight: "600",
          },
        ],
        "body-sm": [
          "12px",
          {
            lineHeight: "18px",
            letterSpacing: "0.02em",
            fontWeight: "400",
          },
        ],
        "label-md": [
          "11px",
          {
            lineHeight: "14px",
            letterSpacing: "0.16em",
            fontWeight: "500",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "0em", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
