/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}"
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "inverse-primary": "rgb(var(--color-inverse-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--color-on-secondary-fixed) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-surface-tint) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "tertiary-container": "rgb(var(--color-tertiary-container) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "on-tertiary": "rgb(var(--color-on-tertiary) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--color-secondary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--color-on-tertiary-fixed) / <alpha-value>)",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "error": "rgb(var(--color-error) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
        "tertiary": "rgb(var(--color-tertiary) / <alpha-value>)"
      },
      borderRadius: {
        DEFAULT: "var(--radius-default)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)"
      },
      spacing: {
        "space-2xl": "var(--spacing-space-2xl)",
        "gutter-mobile": "var(--spacing-gutter-mobile)",
        "margin-mobile": "var(--spacing-margin-mobile)",
        "space-sm": "var(--spacing-space-sm)",
        "space-md": "var(--spacing-space-md)",
        "margin": "var(--spacing-margin)",
        "gutter": "var(--spacing-gutter)",
        "space-xs": "var(--spacing-space-xs)",
        "space-xl": "var(--spacing-space-xl)",
        "space-lg": "var(--spacing-space-lg)",
        "margin-md": "var(--spacing-margin-md)",
        "margin-lg": "var(--spacing-margin-lg)",
        "gutter-lg": "var(--spacing-gutter-lg)"
      },
      fontFamily: {
        "headline-xl-mobile": ["var(--font-headline-xl-mobile)"],
        "headline-lg": ["var(--font-headline-lg)"],
        "headline-sm": ["var(--font-headline-sm)"],
        "headline-md": ["var(--font-headline-md)"],
        "headline-xl": ["var(--font-headline-xl)"],
        "body-lg": ["var(--font-body-lg)"],
        "body-md": ["var(--font-body-md)"],
        "label-sm": ["var(--font-label-sm)"],
        "label-lg": ["var(--font-label-lg)"],
        "body-sm": ["var(--font-body-sm)"],
        "label-md": ["var(--font-label-md)"],
        "headline-lg-mobile": ["var(--font-headline-lg-mobile)"],
        "caption": ["var(--font-caption)"],
        "display-lg-mobile": ["var(--font-display-lg-mobile)"],
        "display-lg": ["var(--font-display-lg)"]
      },
      fontSize: {
        "headline-xl-mobile": ["var(--fs-headline-xl-mobile)", { lineHeight: "var(--lh-headline-xl-mobile)", letterSpacing: "var(--ls-headline-xl-mobile)", fontWeight: "var(--fw-headline-xl-mobile)" }],
        "headline-lg": ["var(--fs-headline-lg)", { lineHeight: "var(--lh-headline-lg)", letterSpacing: "var(--ls-headline-lg)", fontWeight: "var(--fw-headline-lg)" }],
        "headline-sm": ["var(--fs-headline-sm)", { lineHeight: "var(--lh-headline-sm)", letterSpacing: "var(--ls-headline-sm)", fontWeight: "var(--fw-headline-sm)" }],
        "headline-md": ["var(--fs-headline-md)", { lineHeight: "var(--lh-headline-md)", letterSpacing: "var(--ls-headline-md)", fontWeight: "var(--fw-headline-md)" }],
        "headline-xl": ["var(--fs-headline-xl)", { lineHeight: "var(--lh-headline-xl)", letterSpacing: "var(--ls-headline-xl)", fontWeight: "var(--fw-headline-xl)" }],
        "body-lg": ["var(--fs-body-lg)", { lineHeight: "var(--lh-body-lg)", letterSpacing: "var(--ls-body-lg)", fontWeight: "var(--fw-body-lg)" }],
        "body-md": ["var(--fs-body-md)", { lineHeight: "var(--lh-body-md)", letterSpacing: "var(--ls-body-md)", fontWeight: "var(--fw-body-md)" }],
        "label-sm": ["var(--fs-label-sm)", { lineHeight: "var(--lh-label-sm)", letterSpacing: "var(--ls-label-sm)", fontWeight: "var(--fw-label-sm)" }],
        "label-lg": ["var(--fs-label-lg)", { lineHeight: "var(--lh-label-lg)", letterSpacing: "var(--ls-label-lg)", fontWeight: "var(--fw-label-lg)" }],
        "body-sm": ["var(--fs-body-sm)", { lineHeight: "var(--lh-body-sm)", letterSpacing: "var(--ls-body-sm)", fontWeight: "var(--fw-body-sm)" }],
        "label-md": ["var(--fs-label-md)", { lineHeight: "var(--lh-label-md)", letterSpacing: "var(--ls-label-md)", fontWeight: "var(--fw-label-md)" }],
        "headline-lg-mobile": ["var(--fs-headline-lg-mobile)", { lineHeight: "var(--lh-headline-lg-mobile)", letterSpacing: "var(--ls-headline-lg-mobile)", fontWeight: "var(--fw-headline-lg-mobile)" }],
        "caption": ["var(--fs-caption)", { lineHeight: "var(--lh-caption)", letterSpacing: "var(--ls-caption)", fontWeight: "var(--fw-caption)" }],
        "display-lg-mobile": ["var(--fs-display-lg-mobile)", { lineHeight: "var(--lh-display-lg-mobile)", letterSpacing: "var(--ls-display-lg-mobile)", fontWeight: "var(--fw-display-lg-mobile)" }],
        "display-lg": ["var(--fs-display-lg)", { lineHeight: "var(--lh-display-lg)", letterSpacing: "var(--ls-display-lg)", fontWeight: "var(--fw-display-lg)" }]
      }
    }
  },
  plugins: [],
};
